export const getAbbreviationMapping = (): Map<string, string> => {
  const abbreviationMapping = new Map();

  abbreviationMapping.set('=', 'equals');
  abbreviationMapping.set('~ ', 'alternative spelling');
  abbreviationMapping.set('1dual', '1st person dual');
  abbreviationMapping.set('1pl', '1st person plural');
  abbreviationMapping.set('1sg', '1st person singular');
  abbreviationMapping.set('2dual', '2nd person dual');
  abbreviationMapping.set('2pl', '2nd person plural');
  abbreviationMapping.set('2sg', '2nd person singular');
  abbreviationMapping.set('3pl', '3rd person plural');
  abbreviationMapping.set('3sg', '3rd person singular');
  abbreviationMapping.set('acc', 'accusative');
  abbreviationMapping.set('adj', 'adjective');
  abbreviationMapping.set('adv', 'adverb');
  abbreviationMapping.set('art', 'article (def)');
  abbreviationMapping.set('aux', 'auxiliary (verb)');
  abbreviationMapping.set('comp', 'comparative (adj or adv)');
  abbreviationMapping.set('conj', 'conjunction');
  abbreviationMapping.set('conjug', 'conjugation');
  abbreviationMapping.set('dat', 'dative');
  abbreviationMapping.set('def', 'definite (art)');
  abbreviationMapping.set('defect', 'defective');
  abbreviationMapping.set('dem', 'demonstrative (pron)');
  abbreviationMapping.set('e-m', 'einhverjum, einhverju ‘for somebody, something,’ dative');
  abbreviationMapping.set('e-n', 'einhvern, eitthvat ‘somebody, something’ accusative');
  abbreviationMapping.set('e-s', 'einhvers ‘of somebody or something,’ genetive)');
  abbreviationMapping.set('e-t', 'einhvern, eitthvat ‘somebody, something’ accusative');
  abbreviationMapping.set('e-u', 'einhverjum, einhverju ‘for somebody, something,’ dative');
  abbreviationMapping.set('Eng', 'English');
  abbreviationMapping.set('esp', 'especially');
  abbreviationMapping.set('etc', 'et cetera');
  abbreviationMapping.set('ex', 'example');
  abbreviationMapping.set('f ', 'feminine');
  abbreviationMapping.set('fig', 'figurative');
  abbreviationMapping.set('gen', 'genitive');
  abbreviationMapping.set('imp', 'imperative');
  abbreviationMapping.set('impers', 'impersonal (verb)');
  abbreviationMapping.set('indecl', 'indeclinable');
  abbreviationMapping.set('indef', 'indefinite (pron)');
  abbreviationMapping.set('indic', 'indicative');
  abbreviationMapping.set('inf', 'infinitive');
  abbreviationMapping.set('interrog', 'interrogative (adv or pron)');
  abbreviationMapping.set('intrans', 'intransitive (verb)');
  abbreviationMapping.set('leg', 'legal usage');
  abbreviationMapping.set('lit', 'literally');
  abbreviationMapping.set('m ', 'masculine');
  abbreviationMapping.set('MI', 'Modern Icelandic');
  abbreviationMapping.set('mid', 'middle voice');
  abbreviationMapping.set('n ', 'neuter');
  abbreviationMapping.set('neg', 'negative');
  abbreviationMapping.set('neg suff', 'negative suffix');
  abbreviationMapping.set('nom', 'nominative');
  abbreviationMapping.set('num', 'number');
  abbreviationMapping.set('obj', 'object');
  abbreviationMapping.set('OE', 'Old English');
  abbreviationMapping.set('OI', 'Old Icelandic');
  abbreviationMapping.set('ON', 'Old Norse');
  abbreviationMapping.set('ord ', 'ordinal (num)');
  abbreviationMapping.set('part', 'particle');
  abbreviationMapping.set('pers ', 'personal');
  abbreviationMapping.set('pl', 'plural');
  abbreviationMapping.set('poet', 'poetical usage');
  abbreviationMapping.set('poss', 'possessive (pron)');
  abbreviationMapping.set('ppart', 'past participle');
  abbreviationMapping.set('pref', 'prefix');
  abbreviationMapping.set('prep', 'preposition');
  abbreviationMapping.set('pres par', 't present participle');
  abbreviationMapping.set('pres', 'present');
  abbreviationMapping.set('pret-pres', 'preterite-present (verb)');
  abbreviationMapping.set('pron', 'pronoun');
  abbreviationMapping.set('refl', 'reflexive (verb or pron)');
  abbreviationMapping.set('rel', 'relative (pron or particle)');
  abbreviationMapping.set('sb', 'somebody');
  abbreviationMapping.set('sg', 'singular');
  abbreviationMapping.set('sth', 'something');
  abbreviationMapping.set('str', 'strong (adj or verb)');
  abbreviationMapping.set('subj', 'subject');
  abbreviationMapping.set('subjunct', 'subjunctive');
  abbreviationMapping.set('suff', 'suffix');
  abbreviationMapping.set('superl', 'superlative (adj or adv)');
  abbreviationMapping.set('trans', 'transitive (verb)');
  abbreviationMapping.set('transl', 'translation');
  abbreviationMapping.set('usu', 'usually');
  abbreviationMapping.set('var', 'variant');
  abbreviationMapping.set('vb', 'verb');
  abbreviationMapping.set('w ', 'with');
  abbreviationMapping.set('wk', 'weak (adjective or verb)');

  return abbreviationMapping;
};

export default {
  getAbbreviationMapping,
};
